# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Fabric Properties
	minecraft_version=26.2
	loader_version=0.19.3

# Mod Properties
	mod_version = 1.9.4+26.2
	maven_group = eu.midnightdust.motschen
	archives_base_name = rocks
	release_type=release
	curseforge_id=416283
	modrinth_id=Sb5ypgDP

# Dependencies
	fabric_version=0.155.2+26.2
	midnightlib_version=1.9.3+26.2-fabric
	polymer_version=0.17.3+26.2
	factorytools_version=0.11.2+26.2
